services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angkorchat-app
    ports:
      - "5173:5173" # Vite's default dev port
    volumes:
      - ./src:/app/src # Hot reload code changes
      - ./public:/app/public
      - /app/node_modules # Don't overwrite container modules with host
    environment:
      - NODE_ENV=development
    restart: always
