apiVersion: v1
kind: Service
metadata:
  name: angkorchat-service
spec:
  selector:
    app: angkorchat
  ports:
    - protocol: TCP
      port: 80       # Port the Service listens on
      targetPort: 80 # Port the Container is listening on
  type: ClusterIP